### PR TITLE
feature: Allows directors to reset passwords through admin portal

### LINKED ISSUE #514: Add ability to trigger password reset from admin area
In the Users and Staff page, directors should be able to issue a password reset email to any user.

### PR DESCRIPTION
**Pull request by cbaudouinjr**
Allows a director to trigger a password reset. The director will not be allowed to specify a password, rather a 50 character secure password is automatically generated. The user will be emailed recovery instructions for their account. I also improved tests in the user_controller_test file. 

No screenshots as only one new button.

closes #514

### CODE REVIEW

**Review by JeremyRudman — APPROVED** [review]
good code 👍

**Comment by JeremyRudman** [comment]
@peterkos I encountered a error where the email link doesn't let me reset the password. Chris does not encounter this issue so I assume its a problem on my end could you see if you can reset a account through the email

**Review by peterkos — CHANGES_REQUESTED** [review]
Awesome work!


If it's easy to change, can the error message be changed to this?
CleanShot 2021-02-02 at 23 13 30

**Review by peterkos — APPROVED** [review]
On second thought, lets fix password reset message on 3.0; there's a lot of other error messages that need fixing anyways, and given this is a low-traffic feature, we can fix later :)

**Pull request merged**
