### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SangramChavan**
nokogiri is required before running bundle install

### CODE REVIEW

**Comment by sman591** [comment]
Hey @SangramChavan, thanks for chiming in!

`bundle install` itself doesn't require any gems before running it (other than `bundler`, which is installed by default on Ruby 2.6 and above). It takes care of installing all gems, including nokogiri, as part of the installation step.

I'm curious what happened here though - did you run `bundle install` and see a specific error?

Let me know if you have any other questions -- hopefully we can figure out what's going on here.

_Side note: I see you also added a `apt-get install ruby-dev` step here. This installs Ruby globally which could lead to issues later on, and the `apt` repository historically installs a much older version of Ruby. I recommend setting up Ruby with `rbenv`, which helps maintain a clean Ruby install that isn't global. GoRails has a great guide on this; I also just updated our readme to outline this a bit better than it was before. https://gorails.com/setup/ubuntu/19.04_

**Comment by SangramChavan** [comment]
Hello @sman591 sman591,
Yes, I can share a screenshot again in case if you wish to check it.
Was looking for a production install for [IEEEmadC](www.ieeemadc.org) yearly contest.

After creating a droplet followed the following steps :
sudo apt-get update && apt-get upgrade -y
sudo apt-get install ruby-full -y
sudo apt-get install mysql-server mysql-client libmysqlclient-dev
gem install rubygems-update    

git clone https://github.com/codeRIT/hackathon-manager.git
cd hackathon-manager
bundle install
[an error occurred google for it and used the following to install nokogiri]
sudo apt-get install build-essential patch ruby-dev zlib1g-dev liblzma-dev
gem install nokogiri
[installation completed]
bin/rails db:setup 
[error occured]

could not proceed further... but I'm really excited to try and propose our team to use Hackathon Manager.

**Comment by sman591** [comment]
Awesome -- thanks for the context. Could you share that screenshot of the nokogiri error if you still have it?

Please note the README docs for HackathonManager are for _development_ only. Deployment docs are up at https://coderit.org/hackathon-manager/docs/deployment.html, which also note that doing a bare Ruby install on a droplet like this may require further tweaks to the codebase, which are not supported. If you already have a droplet though, I do recommend deploying with Dokku; full docs are available at https://coderit.org/hackathon-manager/docs/deployment-dokku

Let me know if you run into any issues, happy to help get it running!

**Comment by SangramChavan** [comment]
After bundle install command
https://ibb.co/Y87sg47

**Comment by sman591** [comment]
>Command 'bundle' not found, but can be installed with:

This means [bundler](https://bundler.io) isn't installed, which would be the case on Ruby <= 2.5. Can you try running `gem install bundler` and then continue with `bundle install`?

With the first screenshot, were you following the GoRails guide with rbenv? It should set up with Ruby 2.6 by default, which comes with the bundler gem by default (our repo specifies Ruby 2.6.3 in the `.ruby-version` file, which is used by rbenv).

**Pull request closed without merging**
